<a href="https://colab.research.google.com/github/salina-nakarmi/Recommendo/blob/Saksham/Initial_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [31]:
df = pd.read_csv("final_processed.csv")

In [32]:
df.shape

(13567, 11)

In [33]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M,Average-Book-Rating,Rating-Count,Dominant-Age-Group,Genre,Description
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,4.93,14,25-34,Actresses,"In a small town in Canada, Clara Callan reluct..."
1,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,4.21,33,35-44,Fiction,An absorbing narrative of Winnie Louie's life.
2,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,3.09,422,25-34,Fiction,Heart of darkness... In a plush Virginia offic...
3,0452264464,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,3.41,180,25-34,Fiction,WINNER OF THE NOBEL PRIZE IN LITERATURE.
4,0609804618,Our Dumb Century: The Onion Presents 100 Years...,The Onion,1999,Three Rivers Press,http://images.amazon.com/images/P/0609804618.0...,5.68,19,25-34,Humor,The Onion has quickly become the world's most ...

In [34]:
df["Book-Author"].value_counts()

Book-Author
Stephen King              139
Nora Roberts              119
R. L. Stine                78
Danielle Steel             75
Sandra Brown               66
                         ...
Judith Ryan Hendricks       1
David Marion Wilkinson      1
Jonathan Stone              1
JULIE SMITH                 1
Kathryn Reiss               1
Name: count, Length: 4429, dtype: int64

In [35]:
# No null value
df.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-M            0
Average-Book-Rating    0
Rating-Count           0
Dominant-Age-Group     0
Genre                  0
Description            0
dtype: int64

In [36]:
df.shape

(13567, 11)

In [37]:
# There are some duplicate books value name
df["Book-Title"].duplicated().sum()

np.int64(1512)

In [38]:
# Dropped all the duplicated values
df.drop_duplicates(subset =["Book-Title"], inplace=True)

In [39]:
# This line of code will remove some unwanted data that are include inside () words after : , which does not hold much information
df["Book-Title"]=df["Book-Title"].str.split(r'[./(:]').str[0]

In [40]:
wanted_columns = ["ISBN","Book-Title","Book-Author", "Year-Of-Publication","Publisher", "Genre" , "Description"]

In [41]:
df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-M,Average-Book-Rating,Rating-Count,Dominant-Age-Group,Genre,Description
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,4.93,14,25-34,Actresses,"In a small town in Canada, Clara Callan reluct..."
1,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,4.21,33,35-44,Fiction,An absorbing narrative of Winnie Louie's life.
2,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,3.09,422,25-34,Fiction,Heart of darkness... In a plush Virginia offic...
3,0452264464,Beloved,Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,3.41,180,25-34,Fiction,WINNER OF THE NOBEL PRIZE IN LITERATURE.
4,0609804618,Our Dumb Century,The Onion,1999,Three Rivers Press,http://images.amazon.com/images/P/0609804618.0...,5.68,19,25-34,Humor,The Onion has quickly become the world's most ...

In [42]:
# This removes the rows and columns that contains the null value
df_1 = df[wanted_columns]
df_1.dropna(inplace=True)
df_1.head()

/tmp/ipython-input-270660271.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1.dropna(inplace=True)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Genre,Description
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,Actresses,"In a small town in Canada, Clara Callan reluct..."
1,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,Fiction,An absorbing narrative of Winnie Louie's life.
2,0440234743,The Testament,John Grisham,1999,Dell,Fiction,Heart of darkness... In a plush Virginia offic...
3,0452264464,Beloved,Toni Morrison,1994,Plume,Fiction,WINNER OF THE NOBEL PRIZE IN LITERATURE.
4,0609804618,Our Dumb Century,The Onion,1999,Three Rivers Press,Humor,The Onion has quickly become the world's most ...

In [43]:
# This will give the ISBN number of each of the unique books
books_we_have = df_1["ISBN"].unique()
books_we_have

array(['0002005018', '0399135782', '0440234743', ..., '3764501782',
       '3803112133', '0330353349'], dtype=object)

In [44]:
df_1 = df_1.drop_duplicates(subset =["Book-Title"])
df_1 = df_1.reset_index(drop=True)

In [45]:
df_1["Description"][22]

"He gave up the money. He gave up the power. Now all he has left is the law. Michael Brock is billing the hours, making the money, rushing relentlessly to the top of Drake & Sweeney, a giant D.C. law firm. One step away from partnership, Michael has it all. Then, in an instant, it all comes undone. A homeless man takes nine lawyers hostage in the firm's plush offices. When it is all over, the man's blood is splattered on Michael's face--and suddenly Michael is willing to do the unthinkable. Rediscovering a conscience he lost long ago, Michael is leaving the big time for the streets where his attacker once lived--and where society's powerless need an advocate for justice. But there's one break Michael can't make: from a secret that has floated up from the depths of Drake & Sweeney, from a confidential file that is now in Michael's hands, and from a conspiracy that has already taken lives. Now Michael's former partners are about to become his bitter enemies. Because to them, Michael Brock is the most dangerous man on the streets...."

In [46]:
df_1["Combined_feature"] = df_1["Book-Title"] + " " + df_1["Book-Author"] + " " + df_1["Publisher"] + " " + df_1["Genre"] + " " +df_1["Description"]

In [47]:
df_1.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Genre,Description,Combined_feature
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,Actresses,"In a small town in Canada, Clara Callan reluct...",Clara Callan Richard Bruce Wright HarperFlamin...
1,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,Fiction,An absorbing narrative of Winnie Louie's life.,The Kitchen God's Wife Amy Tan Putnam Pub Grou...
2,0440234743,The Testament,John Grisham,1999,Dell,Fiction,Heart of darkness... In a plush Virginia offic...,The Testament John Grisham Dell Fiction Heart ...
3,0452264464,Beloved,Toni Morrison,1994,Plume,Fiction,WINNER OF THE NOBEL PRIZE IN LITERATURE.,Beloved Toni Morrison Plume Fiction WINNER OF...
4,0609804618,Our Dumb Century,The Onion,1999,Three Rivers Press,Humor,The Onion has quickly become the world's most ...,Our Dumb Century The Onion Three Rivers Press ...
5,1841721522,New Vegetarian,Celia Brooks Brown,2001,Ryland Peters &amp; Small Ltd,International cooking,In New Vegetarian Celia Brooks Brown presents ...,New Vegetarian Celia Brooks Brown Ryland Peter...
6,0971880107,Wild Animus,Rich Shapero,2004,Too Far,Fiction,"Wild animus is a search for the primordial, a ...",Wild Animus Rich Shapero Too Far Fiction Wild ...
7,0345402871,Airframe,Michael Crichton,1997,Ballantine Books,Fiction,Three passengers are dead. Fifty-six are injur...,Airframe Michael Crichton Ballantine Books Fic...
8,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,Fiction,When a group of scientists learns how to trave...,Timeline MICHAEL CRICHTON Ballantine Books Fic...
9,0375759778,Prague,ARTHUR PHILLIPS,2003,Random House Trade Paperbacks,Fiction,"A novel of startling scope and ambition, Pragu...",Prague ARTHUR PHILLIPS Random House Trade Pap...

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Initialize the tfidf
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(df_1["Combined_feature"])

In [49]:
tfidf_matrix.shape

(11494, 47729)

In [50]:
sparse_size = (
    tfidf_matrix.data.nbytes +
    tfidf_matrix.indices.nbytes +
    tfidf_matrix.indptr.nbytes
)

print(f"Actual Sparse matrix memory: {sparse_size / (1024 ** 2):.2f} MB")

Actual Sparse matrix memory: 6.13 MB

In [51]:
import sys
print(f"Dense matrix size: {(sys.getsizeof(tfidf_matrix.toarray()))/(1024 **3):.2f} GB")
print(f"There is massive compression that is 99.85% reduction on in the size")

Dense matrix size: 4.09 GB
There is massive compression that is 99.85% reduction on in the size

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute pairwise similarity martix
cosine_sin = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [53]:
indices = pd.Series(df_1.index,index= df_1["Book-Title"]).drop_duplicates()


def recommend_books(title, cosine_sim=cosine_sin, top_n=5):
    # Get the index of the book that matches the title
    idx = indices[title]

    # Get the pairwise similarity scores for that book
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the books based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the top_n most similar books (excluding itself)
    sim_scores = sim_scores[1:top_n+1]

    # Get the book indices
    book_indices = [i[0] for i in sim_scores]

    # Return the top recommended books
    return df_1['Book-Title'].iloc[book_indices]

In [54]:
df_1[df_1["Book-Title"] == "High Tide in Tucson"]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Genre,Description,Combined_feature
8382,0060172916,High Tide in Tucson,Barbara Kingsolver,1995,HarperCollins Publishers,Literary Collections,Barbara Kingsolver has entertained and touched...,High Tide in Tucson Barbara Kingsolver HarperC...

In [55]:
recommend_books("High Tide in Tucson")

5988          High Tide in Tucson
244     Homeland and Other Stories
13                  Pigs in Heaven
243                 The Bean Trees
1801                  Small Wonder
Name: Book-Title, dtype: object

In [56]:
df_1[df_1["Book-Title"] == "Pigs in Heaven"]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Genre,Description,Combined_feature
13,0060168013,Pigs in Heaven,Barbara Kingsolver,1993,Harpercollins,Fiction,"Acclaimed, bestselling author Kingsolver conti...",Pigs in Heaven Barbara Kingsolver Harpercollin...

In [58]:
recommend_books("Pigs in Heaven")

243                           The Bean Trees
8382                     High Tide in Tucson
244               Homeland and Other Stories
5988                    High Tide in Tucson
3214    The Best American Short Stories 2001
Name: Book-Title, dtype: object